'use client'
import { useEffect, useState } from 'react'

export default function SubscriptionAdminPage() {
  const [items, setItems] = useState([]); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true)
  const load = () => { setLoading(true); fetch('/api/admin/subscriptions').then(r => r.json()).then(d => setItems(d.subscriptions || [])).finally(() => setLoading(false)) }
  useEffect(() => { load() }, [])
  const action = async (subscriptionId, action, extra = {}) => { const r = await fetch('/api/admin/subscriptions', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ subscriptionId, action, ...extra }) }); const d = await r.json(); setNotice(d.error || 'Saved.'); if (!d.error) load() }
  const generate = async () => { const planId = window.prompt('Plan: starter, growth, or enterprise', 'growth'); if (!planId) return; const interval = window.prompt('Term: month or year', 'year'); if (!interval) return; const r = await fetch('/api/admin/subscriptions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'generate_code', planId, interval }) }); const d = await r.json(); setNotice(d.code ? `Copy this code now: ${d.code}` : d.error) }
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-6xl"><h1 className="text-2xl font-900 text-slate-950">Subscription administration</h1><p className="mt-1 text-sm text-slate-600">Manual activations, renewals, and single-use codes.</p><div className="mt-4 flex gap-3"><button onClick={generate} className="rounded-lg bg-indigo-800 px-4 py-2 text-sm font-700 text-white">Generate activation code</button><button onClick={load} className="rounded-lg border px-4 py-2 text-sm">Refresh</button></div>{notice && <p className="mt-4 rounded-lg bg-white p-3 text-sm">{notice}</p>}
    <div className="mt-6 overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Clinic</th><th className="p-3">Plan</th><th className="p-3">Status</th><th className="p-3">Ends</th><th className="p-3">Actions</th></tr></thead><tbody>{loading ? <tr><td className="p-4" colSpan="5">Loading…</td></tr> : items.map(s => <tr className="border-t" key={s.id}><td className="p-3 font-600">{s.organizations?.name}</td><td className="p-3 capitalize">{s.plan_id} / {s.interval}</td><td className="p-3">{s.status}</td><td className="p-3">{s.current_period_ends_at ? new Date(s.current_period_ends_at).toLocaleDateString() : '—'}</td><td className="p-3"><div className="flex gap-2"><button className="text-indigo-700" onClick={() => action(s.id, 'activate')}>Activate</button><button className="text-indigo-700" onClick={() => action(s.id, 'renew')}>Renew</button><button className="text-red-700" onClick={() => action(s.id, 'cancel')}>Cancel</button></div></td></tr>)}</tbody></table></div></div></main>
}
